*** Keywords ***

Verify Checkout page "Personal information" loaded



Choose an address "France"

Click Personal Information "Continue" button

Verify Checkout page "Shipping method" loaded

Choose shipping method "My carrier"

Click Shipping method "Continue" button

Verify Checkout page "Payment method" loaded

Choose payment method "Pay by bank wire"

Check "I agree with the terms of service and will adhere to them unconditionally." Checkbox

Click payment method "Continue" button
