*** Variables ***

${CART_PAGE_HEADER} =                       xpath=//*[@id="main"]/div/div[1]/div/div[1]/h1
${CART_PAGE_THUMBNAIL}  =
${CART_PAGE_TRASH_ICON} =                   css=.remove-from-cart > .material-icons
${CART_PAGE_PRODUCT_NAME} =
${CART_PAGE_PRODUCT_PRICE} =
${CART_PAGE_PRODUCT_QUANTITY} =
${CART_PAGE_PRODUCT_TOTAL_PRICE} =
${CART_PAGE_SUBTOTAL} =
${CART_PAGE_TOTAL} =
${CART_PAGE_CHECKOUT_BUTTON} =
