*** Variables ***

${LANDING_PAGE_BRAND_IMAGE}                                         xpath=//img

${LANDING_PAGE_HUMMINGBIRD_PRINTED_T_SHIRT_THUMBNAIL}               xpath=//img[@alt='Hummingbird printed t-shirt']
${LANDING_PAGE_THE_ADVENTURE_BEGINS_FRAMED_POSTER_THUMBNAIL}        xpath=//img[@alt='The adventure begins Framed poster']
${LANDING_PAGE_HUMMINGBIRD_PRINTED_SWEATER_THUMBNAIL}               xpath=//img[@alt='Brown bear printed sweater']
${LANDING_PAGE_THE_BEST_IS_YET_TO_COME_FRAMED_POSTER_THUMBNAIL}     xpath=//img[@alt="The best is yet to come' Framed poster"]
${LANDING_PAGE_THE_BEST_IS_YET_TO_COME_MUG_THUMBNAIL}               xpath=//img[@alt='Mug The best is yet to come']