*** Variables ***
${ORDER_MODAL_BODY} =                           xpath=//*[@id="blockcart-modal"]/div/div/div[2]
${ORDER_MODAL_HEADER} =                         xpath=//*[@id="myModalLabel"]
${ORDER_MODAL_CONTINUE_SHOPPING_BUTTON} =    xpath=//*[@id="blockcart-modal"]/div/div/div[2]/div/div[2]/div/div/button
${ORDER_MODAL_CHECKOUT_BUTTON} =             xpath=//*[@id="blockcart-modal"]/div/div/div[2]/div/div[2]/div/div/a