*** Variables ***

${ORDER_ADDRESS_PAGE_1_HEADER} =                              Personal Information
${ORDER_ADDRESS_PAGE_1_ORDER_AS_GUEST_HEADER} =               Order as Guest
${ORDER_ADDRESS_PAGE_1_SIGN_IN_LINK} =                        Sign In
${ORDER_ADDRESS_PAGE_1_MR_RADIO_BUTTON} =                     Mr.
${ORDER_ADDRESS_PAGE_1_MRS_RADIO_BUTTON} =                    Mrs.
${ORDER_ADDRESS_PAGE_1_FIRST_NAME_BOX} =                      First Name
${ORDER_ADDRESS_PAGE_1_LAST_NAME_BOX} =                       Last Name
${ORDER_ADDRESS_PAGE_1_EMAIL_BOX} =                           Email
${ORDER_ADDRESS_PAGE_1_PASSWORD_BOX} =                        Password
${ORDER_ADDRESS_PAGE_1_BIRTHDAY_BOX} =                        Birthday
${ORDER_ADDRESS_PAGE_1_RECEIVE_OFFERS_CHECKBOX} =             Receive Offers
${ORDER_ADDRESS_PAGE_1_SIGN_UP_FOR_NEWSLETTER_CHECKBOX} =     Sign Up for Newsletter
${ORDER_ADDRESS_PAGE_1_CONTINUE_BUTTON} =                     Continue

${ORDER_ADDRESS_PAGE_2_HEADER} =                              Addresses
${ORDER_ADDRESS_PAGE_2_FIRST_NAME_BOX} =                      First Name
${ORDER_ADDRESS_PAGE_2_LAST_NAME_BOX} =                       Last Name
${ORDER_ADDRESS_PAGE_2_COMPANY_BOX} =                         Company
${ORDER_ADDRESS_PAGE_2_VAT_BOX} =                             VAT
${ORDER_ADDRESS_PAGE_2_ADDRESS_BOX} =                         Address 1
${ORDER_ADDRESS_PAGE_2_ADDRESS_COMPLEMENT_BOX} =              Address 2
${ORDER_ADDRESS_PAGE_2_ZIP_CODE_BOX} =                        Zip Code
${ORDER_ADDRESS_PAGE_2_CITY_BOX} =                            City
${ORDER_ADDRESS_PAGE_2_COUNTRY_DROPDOWN} =                    Country
${ORDER_ADDRESS_PAGE_2_PHONE_BOX} =                           Phone
${ORDER_ADDRESS_USE_THE_SAME_ADDRESS_FOR_INVOICE_CHECKBOX} =  Use the same address for invoice
${ORDER_ADDRESS_PAGE_2_CONTINUE_BUTTON} =                     Continue

${ORDER_ADDRESS_PAGE_3_HEADER} =                              Shipping Method
${ORDER_ADDRESS_PAGE_3_VALORI_AUTOMATION_RADIO_BUTTON} =      Valori Automation
${ORDER_ADDRESS_PAGE3_MY_CARRIER_RADIO_BUTTON} =              My Carrier
${ORDER_ADDRESS_PAGE_3_CONTINUE_BUTTON} =                     Continue

${ORDER_ADDRESS_PAGE_4_HEADER} =                              Payment
${ORDER_ADDRESS_PAGE_4_BANK_WIRE_RADIO_BUTTON} =              Bank Wire
${ORDER_ADDRESS_PAGE_4_CHECK_RADIO_BUTTON} =                  Check
${ORDER_ADDRESS_PAGE_4_AGREE_TO_TERMS_CHECKBOX} =             I agree to the terms of service and will adhere to them unconditionally.
${ORDER_ADDRESS_PAGE_4_PLACE_ORDER_BUTTON} =                  Continue

${ORDER_ADDRESS_PAGE_SUMMARY_SHOW_DETAILS_DROPDOWN} =         Show Details
${ORDER_ADDRESS_PAGE_SUMMARY_SUBTOTAL} =                      Subtotal
${ORDER_ADDRESS_PAGE_SUMMARY_SHIPPING} =                      Shipping
${ORDER_ADDRESS_PAGE_SUMMARY_TOTAL} =                         Tax