*** Variables ***
${SINGLE_PRODUCT_PAGE_HUMMINGBIRD_TSHIRT_HEADER} =              xpath=//*[@id="main"]/div[1]/div[2]/h1
${SINGLE_PRODUCT_PAGE_SIZE_DROPDOWN} =                          id=group_1
${SINGLE_PRODUCT_PAGE_SIZE_DROPDOWN_OPTION_SMALL} =             S
${SINGLE_PRODUCT_PAGE_SIZE_DROPDOWN_OPTION_MEDIUM} =            M
${SINGLE_PRODUCT_PAGE_SIZE_DROPDOWN_OPTION_LARGE} =             L
${SINGLE_PRODUCT_PAGE_SIZE_DROPDOWN_OPTION_XLARGE} =            XL
${SINGLE_PRODUCT_PAGE_SIZE_DROPDOWN_OPTION_XXLARGE} =           XXL
${SINGLE_PRODUCT_PAGE_SIZE_ADD_TO_CART_BUTTON} =                css=.add-to-cart
${SINGLE_PRODUCT_PAGE_DIMENSIONS_DROPDOWN} =                    id=group_3
${SINGLE_PRODUCT_PAGE_DIMENSIONS_DROPDOWN_OPTION_40x60} =       40x60cm
${SINGLE_PRODUCT_PAGE_DIMENSIONS_DROPDOWN_OPTION_60x90} =       60x90cm
${SINGLE_PRODUCT_PAGE_DIMENSIONS_DROPDOWN_OPTION_80x120} =      80x120cm
${SINGLE_PRODUCT_PAGE_QUANTITY_FIELD} =                         id=quantity_wanted

${SINGLE_PRODUCT_PAGE_ADD_TO_CART_BUTTON} =                     xpath=//*[@id="add-to-cart-or-refresh"]/div[2]/div/div[2]/button
${SINGLE_PRODUCT_PAGE_HOME_LINK} =                              xpath=//*[@id="wrapper"]/div/nav/ol/li[1]/a/span
${SINGLE_PRODUCT_PAGE_COLOR_WHITE_RADIO_BUTTON} =               css=.float-xs-left:nth-child(1) .input-color
${SINGLE_PRODUCT_PAGE_COLOR_BLACK_RADIO_BUTTON}=                css=.float-xs-left:nth-child(2) .input-color
